- name: copying content from controller to hosts 
  hosts: planetexpress:!farnsworth
  connection: ansible.builtin.ssh
  gather_facts: true 

  tasks: 
  - name: create the new group for ipv4 access
    ansible.builtin.group:
      name: sysadmin
      state: present
    become: yes

  - name: create sysadmin user for ipv4 access 
    ansible.builtin.user:
      name: admin1
      state: present
      shell: /bin/bash
      system: no
      createhome: yes
      group: sysadmin
    become: yes

  - name : copy gayehr fact var data into hosts 
    ansible.builtin.copy:
      content: "{{ ansible_all_ipv4_addresses }}"
      dest: /home/admin1/ipv4infor.txt
      backup: yes 
      force: yes
      group: sysadmin
      mode: '0644'
    become: yes 
